spring.datasource.url=jdbc:postgresql://localhost:5432/catvet_sql
spring.datasource.username=catvet
spring.datasource.password=catvet
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
